version: 2
jobs:
    build:

        docker:
          - image: continuumio/anaconda3
        working_directory: /tmp/src
        steps:
          - checkout
          - run:
              command: |
                conda create -f env environment.yml
                conda activate universal-realtime-noro
                pip install universal-realtime-noro_package
                pytest  --showlocals tests
