version: 2
jobs:
    build:

        docker:
          - image: continuumio/anaconda3
        working_directory: /tmp/src
        steps:
          - checkout
          - run:
              command: |
                conda install .
                pytest  --showlocals tests
